---
title: R语言处理PCR数据，一步画柱状图、添加显著性标志并实现截断
author: Song Ou-Yang
date: '2021-07-16'
slug: r-pcr
categories:
  - 教程
  - R
tags:
  - R
subtitle: ''
summary: ''
authors: []
lastmod: '2021-08-16T19:34:14+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
比如有如下的一个表格
```{r}
PCR <- read.csv("//mac/Home/Desktop/pcr.csv")
DT::datatable(PCR)
```

```{r}
PCR$dct=PCR$XXX-PCR$GAPDH  ##目的基因Ct-内存基因Ct，即∆Ct
PCR$ddct=PCR$dct-mean(PCR$dct[1:3])  ##∆Ct-对照组Ct均值，即∆∆Ct
PCR$mrna=2^-PCR$ddct  ##取-∆∆Ct的2次放，即-2^∆∆Ct
```

##### 一步出图，`ggpubr`自带计算，均值、标准差、标准误，CI、P值都不在话下
```{r}
library(ggpubr)
ggbarplot(PCR,
          'group',
          'mrna',
          fill = 'group', # 按组填充颜色，当然如果喜欢单色，就用‘black’
          palette = "aaas",  ## "npg", "aaas", "lancet"等主题任意选
          add = "mean_sd",,xlab = F,ylab = 'Relative mRNA expression',legend='none',
          ggtheme = theme_bw()#选一个自己喜欢的背景
)+stat_compare_means(method = 't.test')
```


##### 简单的优化一下，用上`ggprism`这个包，用上`prism`主题，冒充一下上用graphpad做的图
```{r}
## install.packages("ggprism")
library(ggprism)
ggbarplot(PCR,
          'group',
          'mrna',
          fill = "black",
          add = "mean_sd",
          xlab = F,ylab = 'Relative mRNA expression',legend='none',
          ggtheme = theme_prism()
)+stat_compare_means(aes(label = ..p.signif..),  ## 改成星星
                    comparisons = list(c('control','treat')),  ## 添加一下列表
                    method = 't.test')
```

 #### 最后截断一下Y值
以前很少有包可以完美实现这个功能，我以前写过[R做截断柱状图并加显著性统计](https://www.jianshu.com/p/762bcae21f74)可以实现，但Y叔出手写了个`ggbreak`包，完美的就解决了 
```{r}
# install.packages("ggbreak")
library(ggbreak)
p<-ggbarplot(PCR,
          'group',
          'mrna',
          fill = "black",
          add = "mean_sd",
          xlab = F,ylab = 'Relative mRNA expression',legend='none',
          ggtheme = theme_prism()
)+stat_compare_means(aes(label = ..p.signif..),  
                     comparisons = list(c('control','treat')),  
                     method = 't.test')
 ## 只要一句话就解决了，1.5是下轴，15是上轴，当然也可以三截断，定义宽度和高度，具体的自己可以研究
p+scale_y_break(c(1.5, 15) ,scales = c(1,10))
```

